Remove potential panic from path join
nushell/nushell pull request #10012
Opened 2023-08-15 01:47 UTC by 3lvir4

related to issue#10009

# Description

# User-Facing Changes

# Tests + Formatting

# After Submitting

2023-08-15 08:23 UTC, kubouch commented
What is the default span value? I would suspect it is (0,0) which would point at garbage if this case ever happened. Better would be to default to `call.head` which points at the command being called, i.e., at `path join`.

2023-08-15 08:25 UTC, amtoine requested changes
thanks @kubouch, i was just about to add that the current code on this branch gives the following error
```
error[E0277]: the trait bound `nu_protocol::Span: std::default::Default` is not satisfied
    --> crates/nu-command/src/path/join.rs:76:30
     |
76   |                 input.span().unwrap_or_default(),
     |                              ^^^^^^^^^^^^^^^^^ the trait `std::default::Default` is not implemented for `nu_protocol::Span`
     |
note: required by a bound in `std::option::Option::<T>::unwrap_or_default`
    --> /home/amtoine/.rustup/toolchains/1.69.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1020:12
     |
1020 |         T: ~const Default,
     |            ^^^^^^^^^^^^^^ required by this bound in `Option::<T>::unwrap_or_default`
```

using `call.head`, or directly `head` as the default value sounds legit :ok_hand:

2023-08-15 11:58 UTC, 3lvir4 commented
Thanks for the review. I fixed it (I guess). I was tired it seems...

2023-08-15 16:28 UTC, amtoine commented
> Thanks for the review. I fixed it (I guess). I was tired it seems...
>
perfect :ok_hand: 

i just went ahead and fixed the CI (:crossed_fingers:) by formatting the source :yum:

2023-08-16 07:27 UTC, kubouch commented
Thanks!

2023-08-16 07:27 UTC, merged