Completions: add support for doas as for sudo
nushell/nushell pull request #10256
Opened 2023-09-06 21:04 UTC by ZerdoX-x

# Description

Fixes #2047 but for the `doas` command the same way as in #8094
<details>
<summary>Screenshots</summary>
Fixes this difference:

![image](https://github.com/nushell/nushell/assets/49815452/9507fcd9-4cec-4764-ad97-c93106ae2cd0)
![image](https://github.com/nushell/nushell/assets/49815452/59f3e0eb-7756-4c82-85b7-f4d08492ea49)

</details>

# User-Facing Changes
No breaking changes. If people not using `doas`, no difference at all.

# Tests
I have not added any tests since its using same logic as for "sudo". I guess if something would go wrong in this part, sudo tests will cover it?

# Additional context
As a nushell user I could not find a way to implement custom completion for a "sudo like command". Since I can see `sudo` being hardcoded in sources, this is what I propose.

Also I have almost zero knowledge of rust and this is definitely not the clean way:
```
.filter(|content| *content == &String::from("sudo"))
.filter(|context| *content == &String::from("doas"))
```
Please feel free to add commit to refactor and make it better. Thank you :)

2023-09-06 23:11 UTC, sholderbach requested changes
Thanks for giving this a shot!
No fault for not being familiar with Rust yet. In this case your changes not yet add support for command completion after `sudo`/`doas`. In the screenshot you can see that it only suggests files (which I think it will fallback to quite liberally)

2023-09-06 23:11 UTC, sholderbach commented on crates/nu-cli/src/completions/completer.rs
> +                                .filter(|content| *content == &String::from("doas"))
Filtering twice with different predicates would return an empty iterator.
So let's combine them with an or (`||`)

```suggestion
                                .filter(|content| *content == &String::from("sudo") || *content == &String::from("doas"))
```

While we are at it we could make the types a bit nicer (by dereferencing `String` to `&str`)

```suggestion
                                .filter(|content| content.deref() == "sudo" || content.deref() == "doas")
```

2023-09-07 00:14 UTC, ZerdoX-x commented
@sholderbach thank you so much for review <3

Screenshots are just illustration of the problem, not it's solution :D

I've made changes according to your code advice.

2023-09-27 21:52 UTC, ZerdoX-x commented
@sholderbach Hi :)
I've resolved merge conflict and added `doas` to typos false positives so CI check would not complain.
Could you please take a look?

2023-09-28 11:27 UTC, sholderbach commented on crates/nu-cli/src/completions/completer.rs
> +use std::ops::Deref;
Not needed anymore

```suggestion
```

2023-09-28 13:29 UTC, sholderbach approved these changes
Thanks for iterating on this!

I think we should in the future have a way to simply provide a list of commands or a signature that will take external commands and arguments in the trailing position.

But to get this resolved I am fine with landing this right now so we can unblock

2023-09-28 13:29 UTC, merged

2023-09-28 14:27 UTC, fdncred commented
Darn, I forgot about gsudo, that I sometimes use on windows. Now that I think about it, maybe it also has a sudo version of the command?

2023-09-30 21:07 UTC, ZerdoX-x commented on crates/nu-cli/src/completions/completer.rs
> +use std::ops::Deref;
Oh, yeah. Thanks for this

2023-09-30 21:18 UTC, ZerdoX-x commented
> I think we should in the future have a way to simply provide a list of commands or a signature that will take external commands and arguments in the trailing position.

Definitely. As Darren mentioned, it may be some other commands or just any command that wraps other binaries. I could not find a way to implement custom completion with current level of interfaces and/or documentation.

Do you want me to open an issue for this?

2023-09-30 21:47 UTC, fdncred commented
> Do you want me to open an issue for this?

I think so. Thanks!

2023-10-17 18:45 UTC, p00f commented
@ZerdoX-x I used to do it with
```
let doas_completer = {|spans: list<string>|
    do $env.config.completions.external.completer ($spans | skip 1)
}

# This completer will use carapace by default
let external_completer = {|spans|
    let expanded_alias = (scope aliases | where name == $spans.0 | get -i 0.expansion)
    let spans = if $expanded_alias != null  {
        $spans | skip 1 | prepend ($expanded_alias | split words)
    } else {
        $spans
    }

    match $spans.0 {
        doas => $doas_completer
        _ => $carapace_fish_completer
    } | do $in $spans
}
$env.config = {
    completions: {
        external: {
            enable: true
            completer: $external_completer
        }
    }
}
```

2023-10-17 18:46 UTC, p00f commented
note that `pkexec` is another sudo-like command

2023-10-19 23:49 UTC, ZerdoX-x commented
> before this PR, I used to do it with

I think anyways I'll open another issue since there are plenty of commands who accept another program as their first parameter. The most basic example here is `which`, which is not supported by nushell built-in completions. I am not sure this is user friendly, to make people write this in order to support `which`, `exec` and other commands :D

2023-10-20 00:12 UTC, p00f commented
`which` just takes other programs, you don't have to provide completions for the other program's arguments. agree on `exec`