Change `echo` to print when not redirected
nushell/nushell pull request #10338
Opened 2023-09-12 17:00 UTC by jntrnr

# Description

This changes `echo` to work more closely to what users of other shells would expect:

* when redirected, `echo` works as before and sends values through the pipeline
* when not redirected, `echo` will print values to the screen/terminal

# User-Facing Changes

A standalone `echo` now will print to the terminal, if not redirected.

# Tests + Formatting

# After Submitting

2023-09-12 17:52 UTC, kubouch requested changes
@jntrnr The `is_const()` on line https://github.com/nushell/nushell/pull/10338/files#diff-e9ccedd1db0cae905c952bdc08065e33260f2c77475d454e01a2e7d96836ecd2R34 needs to be removed as well

2023-09-12 18:11 UTC, jntrnr commented
@kubouch done

2023-09-12 18:11 UTC, kubouch approved these changes

2023-09-12 18:35 UTC, merged

2023-09-12 23:12 UTC, WindSoilder commented
It looks good!  Just wonder, after the change, `print` can be removed?

2023-09-12 23:59 UTC, jntrnr commented
@WindSoilder - probably. We should deprecate it first

2024-02-19 17:38 UTC, NotTheDr01ds commented
I don't think `print` can be deprecated since it still has the ability to:

* Suppress the newline with `-n/--no-newline`
* Print on `stderr` with `-e/--stderr`

Neither of these are supported by `echo`, right?

And would it really make sense to add `--no-newline` and `--stderr` to `echo` when redirection will suppress output?  E.g. `echo --stderr [ 1 2 3 ] | each {||}` isn't going to do anything.