replace Criterion with Divan
nushell/nushell pull request #12000
Opened 2024-02-27 21:18 UTC by FilipAndersson245

# Description
 
This is a test of changing out the current criterion microbenchmark tool to [Divan](https://nikolaivazquez.com/blog/divan/), a new and more straightforward microbenchmark suit.
Itself states it is robust to noise, and even allow it to be used in CI settings. It by default has no external dependencies and is very fast to run, the sampling method allows it to be a lot faster compared to criterion requiring less samples.
The output is also nicely displayed and easy to get a quick overview of the performance.

![image](https://github.com/nushell/nushell/assets/17986183/587a1fb1-1da3-402c-b668-a27fde9a0657)

# User-Facing Changes

# Tests + Formatting

# After Submitting

2024-02-27 21:25 UTC, FilipAndersson245 commented
I also saw that that [this](https://nikolaivazquez.com/blog/divan/#measure-allocations) exists as well, allowing you to track allocation and deallocations, to easily find whenever a change affects how much memory is being allocated.

2024-02-28 08:05 UTC, FilipAndersson245 commented
btw wooa nushells 12000 PR

2024-02-29 05:59 UTC, FilipAndersson245 commented
Anyone in the core team with a thought on this change, i think this is a good step to simplify the benchmark suit, as its bott faster and require you to look on large graph to get a ballpark of the performance, i also think we should expand the test skit adding for exemplet bechmark of how long std takes to eval etc.

2024-02-29 16:43 UTC, kubouch commented
I don't have a problem with it. The benchmarks are currently not used frequently because we lack any kind of continuous monitoring.

2024-02-29 18:08 UTC, rgwood commented
Agreed with the above. Divan looks nice, Criterion can be difficult to work with and slow. I mostly used it because at the time it was the most popular benchmarking framework for Rust.

I'd be happy to try this out but I'd defer to @amtoine since it will impact his collection of performance data over time.

Thanks for the PR!

2024-02-29 22:54 UTC, rgwood commented
Confirmed with Antoine that he's OK with this. It's a little unfortunate to cause a "break" in our performance tracking history, but the timing is such that there isn't much harm.

2024-03-01 06:51 UTC, rgwood commented
Can you please update `benches/README.md` as part of this PR? Otherwise it will be out of date.

2024-03-01 06:52 UTC, rgwood requested changes
Can you please update benches/README.md as part of this PR? Otherwise it will be out of date.

2024-03-01 16:06 UTC, FilipAndersson245 commented on benches/benchmarks.rs
> +// a way to split things up again.
As i understand this is more a think how benchmarks work in cargo, Divan being more lightweight may reduce the overhead compared to Criterion but I think that can be done later if it fells suitable.

2024-03-01 17:08 UTC, FilipAndersson245 commented
> Can you please update benches/README.md as part of this PR? Otherwise it will be out of date.

Done

2024-03-01 18:02 UTC, rgwood approved these changes

2024-03-01 18:09 UTC, merged