Avoid panic when pipe a variable to a custom command which have recursive call
nushell/nushell pull request #12491
Opened 2024-04-12 02:24 UTC by WindSoilder

# Description
Fixes: #11351

And comment here is also fixed: https://github.com/nushell/nushell/issues/11351#issuecomment-1996191537

The panic can happened if we pipe a variable to a custom command which recursively called itself inside another block.

TBH, I think I figure out how it works to panic, but I'm not sure if there is a potention issue if nushell don't mutate a block in such case.

# User-Facing Changes
Nan

# Tests + Formatting
Done

# After Submitting
Done

2024-04-14 15:41 UTC, IanManske commented
This looks good, although a second set of eyes more familiar with the parser would be nice.

2024-04-14 19:53 UTC, sholderbach commented on crates/nu-parser/src/parser.rs
> +        // def px [] { if { true } else { px } };    # the block px is saved in permanent state.
Typo in the example
```suggestion
        // def px [] { if true { 42 } else { px } };    # the block px is saved in permanent state.
```

2024-04-14 19:57 UTC, sholderbach requested changes
Thanks for fixing the bug you reduced it to.

I think to properly close #11351 this should also include a test using the `$in` variable as this was the initial report by @edhowland and it may very well be possible that the logic for that breaks in the future.

2024-04-14 22:33 UTC, WindSoilder commented
Sure!  I added nearly all test cases, except one in the comment: https://github.com/nushell/nushell/issues/11351#issuecomment-1996191537
Because I can't reproduce the panic on test code :-(

2024-04-15 11:25 UTC, sholderbach commented
Is this a limitation of the whole `nu --testbin=repl` thing?

2024-04-15 22:30 UTC, WindSoilder commented
That case involve nothing with `--testbin=repl`, because it's only panic when run as a script.

But, yeah, I have added a case to test it too :)  Just add a new test fixture file, and run it.

2024-04-22 22:10 UTC, WindSoilder commented
Since relative tests is added, and changes looks good after reviewed, let's land it and try :)

2024-04-22 22:10 UTC, merged