add more tests to the `polars` plugin
nushell/nushell pull request #12719
Opened 2024-05-01 14:24 UTC by maxim-uvarov

# Description

I added some more tests to our mighty `polars`, yet I don't know how to add expected results in some of them. I would like to ask for help.

My experiments are in the last commit: [polars: experiments](https://github.com/nushell/nushell/commit/f7e5e72019ee55b0e6745c1dc405c9a37ced67d1). Without those experiments `cargo test` goes well. 

@ayax79, maybe you'll find time for me please? It's not urgent for sure. 

P.S. I'm very new to git. Please feel free to give me any suggestions on how I should use it better

2024-05-02 18:57 UTC, ayax79 requested changes
Looks good, besides the couple of mentioned issues.

2024-05-02 18:57 UTC, ayax79 commented on crates/nu_plugin_polars/src/dataframe/eager/sample.rs
There needs to be a section to execute the tests. It should look something like this:

```rust
#[cfg(test)]
mod test {
    use super::*;
    use crate::test::test_polars_plugin_command;

    #[test]
    fn test_examples() -> Result<(), ShellError> {
        test_polars_plugin_command(&SampleDF)
    }
}
```

2024-05-02 18:57 UTC, ayax79 commented on crates/nu_plugin_polars/src/dataframe/series/date/as_date.rs
This file also needs to have the test harness code added (see previous comment).

2024-05-03 03:11 UTC, maxim-uvarov commented on crates/nu_plugin_polars/src/dataframe/eager/sample.rs
thanks! done

2024-05-03 03:11 UTC, maxim-uvarov commented on crates/nu_plugin_polars/src/dataframe/series/date/as_date.rs
Thanks! done

2024-05-04 01:14 UTC, merged

2024-05-04 01:15 UTC, fdncred commented
Thanks!