Reduce duplication in history path construction
nushell/nushell pull request #13475
Opened 2024-07-28 05:17 UTC by qfel

# Description
Currently there is a bit of chaos regarding construction of history file paths. Various pieces of code across a number of crates reimplement the same/similar logic:
 - There is `get_history_path`, but it requires a directory parameter (it really just joins it with a file name).
 - Some places use a const for the directory parameter, others use a string literal - in all cases the value seems to be `"nushell"`.
 - Some places assume the `"nushell"` value, other plumb it down from close to the top of the call stack.
 - Some places use a constant for history file names while others assume it.

This PR tries to make it so that the history/config path format is defined in a single places and so dependencies on it are easier to follow:
 - It removes the argument to `get_history_path` (makes it easy to call it to get the path for history in a specific format).
 - Moves code around a bit so that it's easy to map history formats to base file names.
 - Adds a `nu_config_dir` function that returns the nushell configuration directory.
 - Updates existing code to rely on the above, effectively removing duplicate uses of `"nushell"` and `NUSHELL_FOLDER` and assumptions about history file names.

# User-Facing Changes
None

2024-08-04 10:45 UTC, fdncred commented
Do you have time to clean up the conflicts and the ci?

2024-08-05 04:02 UTC, qfel commented
Any idea how to deal with Clippy? What is suggests doesn't compile and the CI doesn't seem to honor warning annotations.

2024-08-05 11:43 UTC, fdncred commented
I got it to compile with 
```
cargo fmt --all
```
and changing
```rust
#[cfg(feature = "plugin")]
use crate::{
    command,
    config_files::{self, setup_config},
};
```
to
```rust
use crate::{
    command,
    config_files::{self, setup_config},
};
```

2024-08-09 04:33 UTC, qfel commented
> This PR makes the history path available as a config.nu setting as $env.config.history.path.

Ah, that's true. I realized I kept finding (and addressing) more and more uses of history and it ended up a bit incoherent. I'll work on this PR a bit more and get back here.

2024-08-09 11:55 UTC, fdncred commented
configurable history path is a separate issue that "reduce duplication". I'd rather see those two concepts split between two PRs. if there is some oversight somewhere, it'll make rolling back safer.

2024-08-12 04:23 UTC, qfel commented
Done (it's still mostly the same, just doesn't have the field)

2024-08-28 04:09 UTC, qfel commented
Anything still missing?

2024-09-26 11:56 UTC, fdncred commented
this kind of fell off my radar. looks like some bit-rot occurred. are you interested in making it green again?

2024-09-27 12:55 UTC, fdncred requested changes
I looked through this again and it generally seems like a good cleanup. Thanks for that. I just had one further comment about nu_config_dir().

2024-09-28 01:20 UTC, qfel commented on crates/nu-path/src/helpers.rs
> +pub fn nu_config_dir() -> Option<AbsolutePathBuf> {
Replaced the last uses of it. Not sure why I didn't do it before.

2024-09-30 20:43 UTC, fdncred commented on crates/nu-path/src/helpers.rs
> +    configutable_dir_path("XDG_DATA_HOME", dirs::data_dir)
All these are spelled wrong.
```suggestion
    configurable_dir_path("XDG_DATA_HOME", dirs::data_dir)
```

2024-09-30 20:44 UTC, fdncred requested changes
Just a spelling issue that needs to be taken care of.

2024-10-09 05:09 UTC, qfel commented
@fdncred can we submit before it needs another rebase?

2024-10-09 13:38 UTC, fdncred commented
Ugh, too late. sorry.

2024-10-11 00:22 UTC, qfel commented
> Ugh, too late. sorry.

Updated, thankfully little work this time.

2024-10-11 12:51 UTC, fdncred approved these changes

2024-10-11 12:51 UTC, merged

2024-10-11 12:51 UTC, fdncred commented
Thanks