Ability to stream output from http endpoints
nushell/nushell pull request #14340
Opened 2024-11-14 15:16 UTC by alex-kattathra-johnson

fixes #14288 

# Description

Adding an optional `--stream` flag to stream output from `http get` command via websocket.

# User-Facing Changes

New optional flag called `--stream`

# Tests + Formatting

Added new tests to test the new flag and to ensure the functionality remains same if the flag isn't set.

# After Submitting

2024-11-17 11:57 UTC, WindSoilder commented
Thank you for the pr!  Would you please share an example about the output when connecting to websocket with `--stream`?  And what if users fire `http get --stream` with not websocket endpoing?

2024-11-17 18:53 UTC, alex-kattathra-johnson commented
It would just return a regular http response, what would you recommend, @WindSoilder ?

2024-12-02 15:39 UTC, WindSoilder requested changes
Sorry for lately reply.  I left some comments

2024-12-02 15:59 UTC, alex-kattathra-johnson commented
Rebased the branched to get a linear commit graph. Gonna make the changes you suggested, @WindSoilder

2024-12-02 16:03 UTC, alex-kattathra-johnson commented on crates/nu-command/src/network/http/client.rs
> +        let rx = self.rx.clone();
I think, because the `rx` is an `Arc` whose reference count needs to be updated for each read.

2024-12-04 12:59 UTC, WindSoilder commented
Thanks!  The implementation looks good to me, but sadly I found tungstenite-rs doesn't support wasm: https://github.com/snapview/tungstenite-rs/issues/417
So there are two ways possible:
1. find another websocket crate which supports wasm, e.g: wasm-bindgen
2. guard the `--stream` flag under `os` feature.

2024-12-04 13:37 UTC, alex-kattathra-johnson commented
@WindSoilder : Ah! I'm good with option #2. What do you think?

2024-12-04 21:08 UTC, cablehead commented
My understanding is that the `http` builtins already stream their body: just checking, this flag / feature is really a websocket upgrade, vs enabling streaming?

2024-12-04 21:12 UTC, alex-kattathra-johnson commented
@cablehead: That is correct, it's possible the `--stream` isn't the best name for the flag. The ureq http client currently attempts to unchunk http responses from endpoints that might not have an explicit EOF, which causes the command to hand indefinitely without any outputs. This was an attempt to get around that for endpoints that are upgradable to websocket.

2024-12-04 21:36 UTC, cablehead commented
> which causes the command to hang indefinitely without any outputs

I wonder if you're seeing this general issue Nushell has with blocking IO: https://github.com/nushell/nushell/issues/12129 ? not sure if it's possible to confirm? 

> it's possible the --stream isn't the best name for the flag

I wonder if it warrants a whole new subcommand, or perhaps it could be driven from the url protocol? e.g. wss://

2024-12-05 17:09 UTC, cablehead commented
Just passing along my takeaway from last night’s open mic: my understanding is the consensus is that advanced HTTP features should be handled through a plugin. The idea is that the built-in HTTP features stay minimal—just enough to support tasks like a plugin that provides WebSocket support—while being easier to maintain and secure. Seeing this as a plugin seems like a great way to make these advanced features happen!?

2024-12-05 23:13 UTC, alex-kattathra-johnson commented
@cablehead: That's a good point, I guess I'm somewhat of a noob to the nushell ecosystem and haven't played around with plugins much. I think a plugin will suffice. I could even just create a plugin for my own personal use and contribute it upstream if others might find it useful.

2024-12-05 23:13 UTC, closed without merging

2024-12-05 23:31 UTC, fdncred commented
Lots of people do that @alex-kattathra-johnson. Take a look at our [awesome-nu repo](https://github.com/nushell/awesome-nu) and see.