normalize special characters in module names to allow variable access
nushell/nushell pull request #14353
Opened 2024-11-15 19:10 UTC by sgvictorino

Fixes #14252

# User-Facing Changes

- Special characters in module names are replaced with underscores when
  importing constants, preventing "expected valid variable name":

```nushell
> module foo-bar { export const baz = 1 }
> use foo-bar
> $foo_bar.baz
```

- "expected valid variable name" errors now include a suggestion list:

```nushell
> module foo-bar { export const baz = 1 }
> use foo-bar
> $foo-bar
Error: nu::parser::parse_mismatch_with_did_you_mean

  × Parse mismatch during operation.
   ╭─[entry #1:1:1]
 1 │ $foo-bar;
   · ────┬───
   ·     ╰── expected valid variable name. Did you mean '$foo_bar'?
   ╰────
```

2024-11-15 21:18 UTC, fdncred commented
@sgvictorino is on fire 🔥!!! We appreciate all your PRs. Thanks.

2024-11-17 11:43 UTC, WindSoilder commented
Thanks!  But there is one thing I'm not sure:
```nushell
module foo-bar { export const baz = 1 }
use foo-bar
$foo-bar.baz
```
Personally I think it's better to export use `baz` variable like `$foo_bar.baz`, to user, after using `foo-bar` and using it with `$` sign, it's using more like a variable rather than a module name.

2024-11-17 13:40 UTC, sholderbach commented
How will this play out with `use <filename>.nu` modules?

2024-11-19 22:14 UTC, 132ikl commented
I think normalizing would be the best option, since then it can align with typical variable name rules and can possibly catch more cases than just hyphens and the dot issue you bring up.

2024-11-22 02:49 UTC, WindSoilder commented
Yeah, @sgvictorino can you update the code to use `$foo_bar.baz`?

2024-11-27 08:40 UTC, WindSoilder requested changes
Sorry for a delay.  Finally I take time to review it.

And I think the solution can be easier.

2024-11-27 08:40 UTC, WindSoilder commented on crates/nu-protocol/src/module.rs
> +                    name_override.unwrap_or(&self.const_name).to_vec(),
I don't think it's necessary to save `const_name` to a module.
We can just `normalize_variable_name` for final_name.

2024-11-29 23:24 UTC, WindSoilder commented on crates/nu-protocol/src/module.rs
> +                    name_override.unwrap_or(&self.const_name).to_vec(),
TBH I can't find a good place either, I think it's ok to make a duplicate function in `module.rs`.

2024-12-02 11:55 UTC, WindSoilder requested changes
Thanks!  Just one thing left, otherwise it looks good to me

2024-12-02 11:55 UTC, WindSoilder commented on crates/nu-protocol/src/module.rs
> +pub fn normalize_module_name(bytes: &[u8]) -> Vec<u8> {
I think it can be private

2024-12-05 13:35 UTC, merged