fix wrong error msg of `save` command on windows
nushell/nushell pull request #14699
Opened 2024-12-30 04:49 UTC by Chen1Plus

fixes #14664 

# Description

Now,

```nu
"aaa" | save -f ..
```

returns correct error message on windows.

Note that the fix introduces a TOCTOU problem, which only effects the error message. It won't break any workload.

# User-Facing Changes

The fix won't break any workload.

# Tests + Formatting

I have run tests **only on windows**.

# After Submitting

The fix doesn't need to change documentation.

2024-12-30 14:40 UTC, WindSoilder requested changes
Thanks!  Can you add a test for it?

2024-12-31 03:00 UTC, Chen1Plus commented
Yeah of course, but where should I add it? Although the `save` command is used in several tests, I didn't see a specific test for it.

2024-12-31 03:32 UTC, WindSoilder commented
Yup, you can put the test under `tests/commands/save.rs`

2024-12-31 11:34 UTC, Chen1Plus commented
The test is added.

2024-12-31 13:46 UTC, WindSoilder commented
Oh, sorry.  I mislead the test position :-(  It should be put in `crates/nu-command/tests/commands/save.rs`.
You should see some testing for `save` command in that file, you can just add your test there.

2025-01-01 02:46 UTC, Chen1Plus commented
Fine.

2025-01-06 23:36 UTC, WindSoilder approved these changes
Thanks!  LGTM

2025-01-06 23:36 UTC, merged