Filter out empty glob patterns to "glob" command
nushell/nushell pull request #6707
Opened 2022-10-12 01:58 UTC by KyleRAnderson

# Description

An empty argument to the "glob" command will now produce an empty result. Working towards nushell/nushell#6653, these changes only touch the `glob` command without changing globs used in cases like `rm ""`. Addressing `nu-glob` will be done in a follow-up PR.

# Tests

Make sure you've done the following:

- [x] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

2022-10-12 11:42 UTC, sholderbach requested changes
Awesome thanks for picking up this issue!
Can you run `cargo fmt --all` on the project to make the CI happy?

I have a minor comment about the error handling spans.

A question for the team would be if we want to pass silently or if we want to consider `glob ""` to be a hard error out of the box.

2022-10-12 11:42 UTC, sholderbach commented on crates/nu-command/src/filesystem/glob.rs
> +        if glob_pattern.item.is_empty() { return Ok(PipelineData::new(Span::new(0, 0))); }
The `Span::new(0, 0)` doesn't convey helpful information if you want to backtrack helpful information for error handling. The `span` in scope from `call.head` will point to the command at hand `glob` (not at the argument, but that is up for debate what is more useful here.)

2022-10-12 13:39 UTC, KyleRAnderson commented
Another question I had: I wasn't able to find tests for the `glob` command, would someone mind pointing me to the right place for these?

2022-10-12 14:17 UTC, KyleRAnderson commented
I've switched to treating an empty glob string as an error in 329c517e627412f5097b6fb8ab879d75693998a2. Once we hear from the team, if we want to go back to silently ignoring it, we can revert this commit.

What it looks like with this change:
![image](https://user-images.githubusercontent.com/22606608/195367479-47210ea1-f9af-4173-8245-5dec5645d2d0.png)

2022-10-13 13:57 UTC, fdncred commented
> I've switched to treating an empty glob string as an error ...

I like this much better.

2022-10-13 14:14 UTC, KyleRAnderson commented
> There may also be changes needed to the nu-glob crate for this issue

There is, in these changes I'm just solving the issue with `glob ""`, but this doesn't solve the equivalent issue with `rm ""` which I assume uses `nu-glob`. I'm planning on addressing the second part in a follow-up PR.

2022-10-15 14:39 UTC, KyleRAnderson commented
I just finished adding some extremely basic tests that check the behaviour of `glob` when an empty argument is passed, as well as a test to check that `glob '*'` still works. I think this one should be ready for review now, thanks for all the feedback so far.

2022-10-15 14:55 UTC, sholderbach approved these changes
Awesome thanks! Great to have more tests on those basic edge cases.

2022-10-15 16:00 UTC, merged