Make `seq` return a `ListStream` where possible.
nushell/nushell pull request #6910
Opened 2022-10-26 09:14 UTC by merelymyself

# Description

Significant perf improvements as well: try something like `seq 1 100000000000` and observe how it is streaming correctly.

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [x] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [ ] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo test --workspace --features=extra` to check that all the tests pass

# Documentation

- [ ] If your PR touches a user-facing nushell feature then make sure that there is an entry in the documentation (https://github.com/nushell/nushell.github.io) for the feature, and update it if necessary.

2022-10-26 09:34 UTC, sholderbach requested changes
That sounds like a worthwhile improvement, especially as in most cases you don't actually care about the small value being emitted.

But I think for correctness reasons, we should change the implementation to use the most appropriate numeric type. Ints when the bounds are ints and floats if float intervals are requested.

2022-10-26 09:34 UTC, sholderbach commented on crates/nu-command/src/generators/seq.rs
> +        let int_stream: bool = first.fract() == 0.0 && step.fract() == 0.0;
I don't want to trust float precision for any precise counting. We should specialize the implementation to either use a `Counter<i64>` or `Counter<f64>`.

2022-10-26 09:34 UTC, sholderbach commented on crates/nu-command/src/generators/seq.rs
> +    int: bool,
I think this can be generic.

2022-10-27 21:27 UTC, sholderbach commented on crates/nu-command/src/generators/seq.rs
> +    is_float_sequence: bool,
Mhh, the data is still coming in as float and may have lost precision. Could we just pass in the `Counter`?

2022-11-05 12:00 UTC, fdncred commented
Hey @merelymyself, do you have time to continue working on this one? Seems like you've been busy recently and haven't got back to it.

2022-11-17 22:23 UTC, sholderbach commented
This has been kind of overtaken by #7045, but should now be easier to make consistently lazy.

2022-12-06 16:17 UTC, closed without merging

2022-12-06 16:38 UTC, fdncred commented
> Hello! Sorry for the long period of inactivity...

Hey! It's @merelymyself!!! It's so glad to see you back here. Welcome again!