chore: chrono_update
nushell/nushell pull request #7132
Opened 2022-11-14 15:03 UTC by Decodetalkers

Log: chrono_update

# Description

upgrade chrono to 0.4.23

# Major Changes

If you're considering making any major change to nushell, before starting work on it, seek feedback from regular contributors and get approval for the idea from the core team either on [Discord](https://discordapp.com/invite/NtAbbGn) or [GitHub issue](https://github.com/nushell/nushell/issues/new/choose).
Making sure we're all on board with the change saves everybody's time.
Thanks!

# Tests + Formatting

Make sure you've done the following, if applicable:

- Add tests that cover your changes (either in the command examples, the crate/tests folder, or in the /tests folder)
  - Try to think about corner cases and various ways how your changes could break. Cover those in the tests

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace --features=extra` to check that all tests pass

# After Submitting

* Help us keep the docs up to date: If your PR affects the user experience of Nushell (adding/removing a command, changing an input/output type, etc.), make sure the changes are reflected in the documentation (https://github.com/nushell/nushell.github.io) after the PR is merged.

2022-11-14 15:04 UTC, Decodetalkers commented
The value in the example should be definite value.. so.. I don't know..caculate it myself maybe?

2022-11-14 15:22 UTC, Decodetalkers commented
crates/nu-command/src/dataframe/values/nu_dataframe/conversion.rs 
is not in the module... why it can be scanned..

2022-11-14 17:56 UTC, dbuch commented on crates/nu-command/src/conversions/into/datetime.rs
> +                    val: Utc.timestamp_opt(1614434100, 0).unwrap().into(),
Ci will be happy about expect() i think.

Utc.timestamp_opt(1614434100, 0).expect("non-leap seconds since unix epoch").into()

2022-11-16 02:23 UTC, fdncred commented on crates/nu-command/src/conversions/into/datetime.rs
> +                    val: Utc.timestamp_opt(1614434100, 0).unwrap().into(),
We try to minimize `expect()` as well, although you're right that ci doesn't check for it.

2022-11-16 02:52 UTC, Decodetalkers commented on crates/nu-command/src/conversions/into/datetime.rs
> +                    val: Utc.timestamp_opt(1614434100, 0).unwrap().into(),
> We try to minimize `expect()` as well, although you're right that ci doesn't check for it.

But there is not expect at all.. I can only use unwrap..

2022-11-17 01:51 UTC, rgwood commented
Hi @Decodetalkers, I'm not comfortable merging this yet.

It looks like you've added several `panic!()` and `expect()` calls in this PR. Are you confident that your change will not crash Nushell? If so, why?

2022-11-19 06:43 UTC, Decodetalkers commented
> Hi @Decodetalkers, I'm not comfortable merging this yet.
> 
> It looks like you've added several `panic!()` and `expect()` calls in this PR. Are you confident that your change will not crash Nushell? If so, why?

I have handled the expects in `example`, but I have no idea about how to handle those one in `windows.rs`

2022-11-19 11:50 UTC, fdncred requested changes
The only thing that I really object to here are the error messages that say `Maybe something error with your time`. Can you change them to something like `Error converting {:?} to timestamp`, where you fill in the {:?} part?

Generally `expect()` and `unwrap()` is allowed in tests but not in other place. We try to keep `expect()` to a minimum although our CI allows them. I haven't tried but I'm wondering if you can use `?` to remove some of these expects, like `.as_i64()?`? If not, maybe more `match` error handling?

2022-11-21 01:34 UTC, fdncred commented
@Decodetalkers Thanks for the changes but `Maybe something error with your time` is not proper grammar, which is why I suggested something different.

2022-11-23 16:15 UTC, fdncred commented
I'm thinking that the wording still needs to change.  Try this.

Change this
```
"Given local time representation is invalid.\nThis can occur when, for example, the positive timezone transition."
```
To this
```
The given local datetime representation is invalid.
```

And then change this
```
There maybe something is wrong with your time\nThis can occur when, for example, the positive timezone transition."
```
To this
```
Their given datetime representation is unsupported.
```

2022-11-25 20:44 UTC, fdncred approved these changes
I tweaked some of the error messages again. I requested the wrong thing. Doh! and one was missed. Thanks. After it goes green I think it's ok.

2022-11-26 18:19 UTC, merged