changes Reqwest to Ureq.
nushell/nushell pull request #8320
Opened 2023-03-04 20:12 UTC by FilipAndersson245

# Description

_(Thank you for improving Nushell. Please, check our [contributing guide](../CONTRIBUTING.md) and talk to the core team before making major changes.)_

This pull request removes `Reqwest` and replaces it with `Ureq` to remove some of our dependencies, giving us faster compile times as well as smaller binaries. `Ureq` does not have an async runtime included so we do not need build heavy dependencies such as `Tokio`. From older tests I had the number of build units be reduced from `430 -> 392`.
The default of `Ureq` uses `Rustls` but it has been configured to instead use `native_tls` which should work exactly the same as the `tls` works now. 
I removed `content-length` from the http commands as after refactoring i did not see a reason to have it available, correct me if this is something we should preserve.

In the medium, to long term, we should maybe consider changing to `rustls` to have the same `tls` on all platforms.

# User-Facing Changes

_(List of all changes that impact the user experience here. This helps us keep track of breaking changes.)_

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

2023-03-04 21:08 UTC, rgwood commented
Thanks! Building it now and... huh:
![image](https://user-images.githubusercontent.com/26268125/222928746-020b8ea1-af99-42ea-b974-b3667e0066f0.png)

Doesn't seem right that we need to build rustls, that's weird.

2023-03-04 21:16 UTC, FilipAndersson245 commented
> Thanks! Building it now and... huh: ![image](https://user-images.githubusercontent.com/26268125/222928746-020b8ea1-af99-42ea-b974-b3667e0066f0.png)
> 
> Doesn't seem right that we need to build rustls, that's weird.

Yes that seem weird, think i need to change some feature when including ureq crate so it does not default to rustls when building.

2023-03-04 21:38 UTC, jntrnr commented
Can we still download from an https site if we disable tls?

2023-03-04 21:49 UTC, FilipAndersson245 commented
> Can we still download from an https site if we disable tls?

I belive as long as you use the tls adapter it should work fine,
![image](https://user-images.githubusercontent.com/17986183/222930123-38cee7a3-5041-4325-badc-0c7af0c08e21.png)
We just manually configure Ureq to use the native_tls crate.

2023-03-04 22:10 UTC, rgwood commented
Some numbers for Nu executable size (in megabytes):

|  OS  | Build command| Size before PR |  Size after PR | 
|---|---|---|---|
| Linux  | cargo build --release --features=static-link-openssl  | 27.1  | 25.4  | 
|  Linux | cargo build --release  | 24.7  | 22.9  | 
| Windows  | cargo build --release  |  23.4 | 21.7  |

2023-03-04 22:34 UTC, rgwood commented
I can confirm that `http get` still checks HTTPS certificates. However, the error messages are a little worse after this change; if a certificate is broken they no longer say why.

### Before

![image](https://user-images.githubusercontent.com/26268125/222931485-ddb83895-ddc0-4fce-aefd-dfbb3b22ce0e.png)

### After

![image](https://user-images.githubusercontent.com/26268125/222931450-137eebbc-5910-40c2-972a-886745cf3782.png)

Not sure how difficult that is to fix. As an aside, maybe we should create some tests for invalid certificates using badssl.com.

2023-03-05 01:17 UTC, rgwood commented
`cargo build` on Linux goes from 431 crates to 390 crates. 👍 

I've done some benchmarking of build times and on my desktop (Linux, 12900K, `mold` linker) this PR reliably gives a 6% speedup for clean debug builds and 4% for incremental debug builds. Nice to see.

Benchmarking scripts for future reference:

```bash
# benchmark clean build
let output = "times.txt"
def println () { char nl | save --append $output }
mut all_times = [];

for i in 0..10 {
    cargo clean

    let time = (timeit { cargo build })
    $time | to text | save --append $output
    println
    $all_times ++= [$time]
}

let avg_time = ($all_times | math avg)
"Average time: \n" | save --append $output
$avg_time | to text | save --append $output
println
```

```bash
# benchmark an incremental build after making a tiny change to a command
let output = "incremental-times.txt"
def println () { char nl | save --append $output }

cargo build

mut all_times = [];

for i in 0..40 {
    # make a meaningless modification to a command
    char nl | save --append crates/nu-command/src/system/sys.rs
    let time = (timeit { cargo build })
    $time | to text | save --append $output
    println
    $all_times ++= [$time]
}

let avg_time = ($all_times | math avg)
"Average time: \n" | save --append $output
$avg_time | to text | save --append $output
println```

2023-03-05 17:04 UTC, rgwood commented
@FilipAndersson245 Do you have time to look into the error messages for SSL failures? It would be nice to tell users something more specific than “native_tls connect failed”

2023-03-05 21:20 UTC, FilipAndersson245 commented
I did an update to TLSerror messages, but it seems difficult to track specific types of error
I added a case for connection errors
![image](https://user-images.githubusercontent.com/17986183/222986604-bd0730ec-c3b8-4cf9-baa2-d38e6c1361f6.png)
Does this look ok? It seems harder detect errors more specific then [this](https://docs.rs/ureq/latest/ureq/enum.ErrorKind.html) related to the http transport.

2023-03-05 21:30 UTC, rgwood requested changes
Looks good thanks! Just 2 small comments.

2023-03-05 21:30 UTC, rgwood commented on crates/nu-command/src/network/http/client.rs
> +                .map(|(a, b)| (&**a, &**b))
Probably best to use `as_str()` instead of `&**`

2023-03-05 21:30 UTC, rgwood commented on crates/nu-command/src/network/http/client.rs
> +                .map(|(a, b)| (&**a, &**b))
Probably best to use `as_str()` instead of `&**`

2023-03-05 21:31 UTC, rgwood commented
> I did an update to TLSerror messages, but it seems difficult to track specific types of error I added a case for connection errors ![image](https://user-images.githubusercontent.com/17986183/222986604-bd0730ec-c3b8-4cf9-baa2-d38e6c1361f6.png) Does this look ok? It seems harder detect errors more specific then [this](https://docs.rs/ureq/latest/ureq/enum.ErrorKind.html) related to the http transport.

Yeah, that looks much better thanks. Would be nice to display the underlying error, but I think that will require some changes in `ureq`.

2023-03-05 21:49 UTC, FilipAndersson245 commented
Don't know why MacOS CI builds fail now? 🤔

2023-03-05 22:06 UTC, sholderbach commented
> Don't know why MacOS CI builds fail now? 🤔

Those are our regular and highly annoying flaky plugin tests. They seem to have an allergic reaction to Apple(s).

2023-03-05 22:48 UTC, rgwood approved these changes
Let's give this a try. Thanks @FilipAndersson245!

2023-03-05 22:48 UTC, merged