Move unit test runner to standard library
nushell/nushell pull request #8850
Opened 2023-04-10 21:03 UTC by presidento

Move test runner to standard library.
Originated from #8819 

# After Submitting

I'll update the documentation about testing: http://www.nushell.sh/book/testing.html

2023-04-11 08:57 UTC, presidento commented
@amtoine I put the run-tests command into `mod.nu`. If you want a separate file for it, please tell me how to do it.

2023-04-11 17:10 UTC, amtoine requested changes
i have a look at how to put this in a module :+1:

2023-04-11 17:10 UTC, amtoine commented on crates/nu-std/lib/mod.nu
> +export def xxx [] {}
i think we do not want that :wink:

2023-04-11 17:34 UTC, amtoine commented
> @amtoine I put the run-tests command into `mod.nu`. If you want a separate file for it, please tell me how to do it.
>
something you can do
- let's say you move the commands from `crates/nu-std/lib/mod.nu` to something like `crates/nu-std/lib/testing.nu`
- then you can apply [`patch.diff`](https://github.com/nushell/nushell/files/11203214/patch.txt)

a bit hacky for now but that should work i think as `std testing run` :+1: 

> **Warning**
> you can NOT do `use std testing` and then `testing run` for now :relieved:

2023-04-11 17:43 UTC, presidento commented
Applied, thanks. (I cannot test it in my current computer.)

2023-04-11 17:43 UTC, presidento commented on crates/nu-std/lib/mod.nu
> +export def xxx [] {}
Yeah, sorry.

2023-04-12 07:35 UTC, presidento commented
I moved the test-related stuff to `testing.nu`: the assert commands and the test runner

2023-04-12 16:21 UTC, presidento commented
It failed with an unrelated error.

2023-04-12 17:57 UTC, amtoine approved these changes
hey, you know what, that looks good :star_struck: 

if we find things to tweak, we can address them later :relieved: 

thanks for all this and let's merge it :muscle:

2023-04-13 19:46 UTC, merged