add -u flag to cp, mv comamnd
nushell/nushell pull request #9214
Opened 2023-05-17 10:11 UTC by WindSoilder

# Description
Closes: #7853

I found that I want this feature too...

So I take over it, sorry for that @VincenzoCarlino 

# User-Facing Changes

# Tests + Formatting

# After Submitting

2023-05-19 09:32 UTC, amtoine requested changes
this looks like it's working just fine to me :ok_hand: 

i'm just wondering if we should add two tests to make sure the copy works indeed when the source is newer than the destination :thinking: 
currently we only test when source is older :open_mouth:

2023-05-20 15:16 UTC, WindSoilder commented
Thanks for your review!  I've added one more action in the test case to match relative scenario

2023-05-20 15:28 UTC, amtoine approved these changes
thanks @WindSoilder :blush:

2023-05-20 16:48 UTC, rgwood approved these changes

2023-05-20 16:48 UTC, merged