fix cd permissions when user belongs to group
nushell/nushell pull request #9531
Opened 2023-06-26 09:49 UTC by WindSoilder

# Description

Fixes: #9498

Actually we don't need this pr if the upstream pr is merged: https://github.com/ogham/rust-users/pull/45

But it doesn't have any commit since 2021, and the author seems not active on github now,  I think we have to copy the function into nushell to get relative issue fixed...

# User-Facing Changes

# Tests + Formatting

# After Submitting

2023-06-27 14:57 UTC, JakeSiFive approved these changes
I'm not a nushell maintainer but this looks good to me!

2023-06-28 01:32 UTC, WindSoilder commented
@JakeSiFive Hi, would you please have a test to see if it works for you?

I have tested it locally and it's fine.

2023-06-29 20:17 UTC, JakeSiFive commented
Is there anything else I can do or info I can provide to help push this along?

2023-06-29 21:01 UTC, sholderbach requested changes
I think we should be a bit more explicit about any `unsafe` code we have as this is not as common in the nu code base.

So I tried to add some comments.

Other than that I think we are good to go with vendoring this code for now.

2023-06-30 06:49 UTC, WindSoilder commented on crates/nu-command/src/filesystem/cd.rs
> +        let name = CString::new(username.as_ref().as_bytes()).expect("not valid cstring");
Yeah I agree, that's a good point :)

2023-06-30 06:49 UTC, WindSoilder commented on crates/nu-command/src/filesystem/cd.rs
> +        let res = unsafe { libc::getgrouplist(name.as_ptr(), gid, buff.as_mut_ptr(), &mut count) };
Oh, that's really nice!  Thanks for the SAFETY comment

2023-06-30 06:51 UTC, WindSoilder commented
Thanks for your carefully consideration @sholderbach.  All of them make good points

2023-06-30 09:02 UTC, sholderbach approved these changes
Thanks!

2023-06-30 09:03 UTC, merged

2023-06-30 13:56 UTC, JakeSiFive commented
Thanks everyone!