Fix output signature of `split chars`/`words`
nushell/nushell pull request #9739
Opened 2023-07-19 23:01 UTC by sholderbach

# Description
Those two commands do *not* vectorize over the input in the pure sense
as they currently perform a flat map. They thus return a single list
even when given a list as input.

Only updates the signature, doesn't change behavior.

2023-07-20 16:32 UTC, amtoine requested changes
i think there are some behaviour changes in this PR :thinking: 

```nushell
["foo" "bar"] | split chars
```
did not work before this PR, now it gives
```
╭───┬───╮
│ 0 │ f │
│ 1 │ o │
│ 2 │ o │
│ 3 │ b │
│ 4 │ a │
│ 5 │ r │
╰───┴───╯
```

and
```nushell
["hello world" "foo bar"] | split words
```
did not work before this PR, now it gives
```
╭───┬───────╮
│ 0 │ hello │
│ 1 │ world │
│ 2 │ foo   │
│ 3 │ bar   │
╰───┴───────╯
```

i'm not saying this is a bad thing, but we should probably mention this in the PR description and add an example to both?

i mean i'm not sure i would have seen that feature without an example :thinking:

2023-07-20 18:05 UTC, sholderbach commented
I think we shouldn't consider restoring behavior that worked before #9680 a breaking change yet as it was working in 0.82

I put this one into a separate PR as I think the behavior is a bit surprising. We may want to discuss changing the flat_map to a map so I intend to raise awareness for future folks looking at the command.

2023-07-20 23:57 UTC, fdncred commented
It seems like the behavior of
```
["foo" "bar"] | split chars
```
should be more like
```
❯ ["foo" "bar"] | each {|r| $r | split chars} | table -e
╭───┬───────────╮
│ 0 │ ╭───┬───╮ │
│   │ │ 0 │ f │ │
│   │ │ 1 │ o │ │
│   │ │ 2 │ o │ │
│   │ ╰───┴───╯ │
│ 1 │ ╭───┬───╮ │
│   │ │ 0 │ b │ │
│   │ │ 1 │ a │ │
│   │ │ 2 │ r │ │
│   │ ╰───┴───╯ │
╰───┴───────────╯
```
rather than
```
❯ ["foo" "bar"] | each {|r| $r | split chars} | flatten
╭───┬───╮
│ 0 │ f │
│ 1 │ o │
│ 2 │ o │
│ 3 │ b │
│ 4 │ a │
│ 5 │ r │
╰───┴───╯
```

And the same type of thing with `split words`. i think it's a little surprising to auto-flatten.

2023-07-21 07:40 UTC, amtoine commented
@sholderbach 
oooh i see :+1: 
i've never used the vectorization of `split chars` and `split words` :wink: 

@fdncred 
agree it's surprising imo :thinking: 
this is why i propose to at least add an example with that vectorization to show users how this works.

2023-07-21 07:41 UTC, amtoine commented
and not flattening automagically sounds sensible :+1:

2023-07-21 12:06 UTC, sholderbach commented
Marking as draft. When I get to it I will change the flat_map to a map.

2023-07-23 21:34 UTC, sholderbach commented
Updated to now map regularly and not flatten automagically.

2023-07-23 22:06 UTC, fdncred approved these changes
I tested it and the output is much better now. Thanks!

2023-07-23 22:06 UTC, merged