Restore Ctrl R behavior to history menu
nushell/nushell pull request #9862
Opened 2023-07-30 11:05 UTC by SUPERCILEX

Was changed by https://github.com/nushell/nushell/commit/345c00aa1ee6abeb3591a87a58b809748799d4b2 (hopefully unintentionally). The `search_history` action overrides the history menu action.

2023-07-30 12:34 UTC, fdncred commented
I think it was changed on purpose in order for the config.nu to match the code. So, if you type `nu -n --no-std-lib` ctrl+r will open the history menu.

2023-07-30 12:51 UTC, SUPERCILEX commented
Let's fix it in the code too then, or is the problem that the no-std-lib variant doesn't have a history menu? Reverse search is a huge downgrade from the history menu, so I think being pragmatic rather than consistent is way more important here. Though if we can fix it in the code too, that's great.

2023-07-30 13:08 UTC, fdncred commented
We definitely shouldn't have 2 items mapped to ctrl+r but I'm not sure what the fix should be.

2023-07-30 13:13 UTC, fdncred commented
ok, after looking at both of these, reverse_search stinks. IMO, We should definitely map the history_menu to ctrl+r but that change would probably have to happen in reedline to make it a default.

2023-07-30 13:31 UTC, SUPERCILEX commented
> reverse_search stinks

Lol my reaction exactly.

> would probably have to happen in reedline to make it a default

I'm not sure what this involves and unfortunately I won't have the time to look into it. Do you want to create an issue/pr, close this one, and take over for me?

2023-07-30 17:29 UTC, amtoine requested changes
i think as @fdncred said, the Rust side, maybe in Reedline, will have to be updated accordingly :yum:

2023-08-06 11:40 UTC, fdncred commented
closing this in favor of https://github.com/nushell/nushell/pull/9930

2023-08-06 11:40 UTC, closed without merging

2023-08-06 12:19 UTC, SUPERCILEX commented
Thanks!