Fix 9156 endian consistency
nushell/nushell pull request #9873
Opened 2023-07-31 07:45 UTC by herobs

- fixed #9156

# Description
I'm trying to fix the problems mentioned in the issue. It's my first attempt in Rust. Please let me know if there are any problems.

# User-Facing Changes
- The `--little-endian` option dropped, replaced with `--endian`.
- Add the `--compact` option to the `into binary` command.

2023-07-31 11:49 UTC, fdncred commented on crates/nu-command/src/conversions/into/binary.rs
> +            .switch("compact", "output without padding zeros", None)
Instead of `None` here, it seems like we should have a shortcut like `Some('c')`

2023-07-31 11:57 UTC, fdncred commented on crates/nu-command/src/conversions/into/binary.rs
> +                let (val, _) = val.split_at(idx + 1);
This `val.split_at` surprised me. It looks like we're just taking the last 0 off until there are no more zeros. This makes my "spidey sense" go off as not being the right way to handle this, but I could be wrong.

2023-07-31 12:49 UTC, herobs commented
I have no idea how to test the big-endian branch. Please give me some hints if you have any.

2023-07-31 13:18 UTC, fdncred commented on crates/nu-command/src/conversions/into/int.rs
> +                None,
We prefer to have shortcuts where we can like `Some('e')` here vs `None`.

2023-07-31 16:08 UTC, jntrnr commented on crates/nu-command/src/conversions/into/int.rs
> -            .switch("little-endian", "use little-endian byte decoding", None)
Removing `--little-endian` makes this a bit harder to read (compared to `--endian little`

2023-08-05 08:29 UTC, amtoine requested changes
thanks for the new tests, i think it's great :pray:

2023-08-05 08:29 UTC, amtoine commented on crates/nu-command/tests/commands/mod.rs
> +mod convertions;
i just think this should be called "*conversions*", not "*convertions*", right? :open_mouth:

2023-08-05 08:30 UTC, amtoine commented
running the CI to see if the test pass :wink:

2023-08-05 08:37 UTC, amtoine commented on crates/nu-command/tests/commands/mod.rs
> +mod convertions;
thanks :blush: 

done in eb6d9f8

2023-08-24 12:08 UTC, fdncred commented
let's move forward with this, thanks!

2023-08-24 12:08 UTC, merged